apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mm-api-gateway-ingress-view
  namespace: {{ .Release.Namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.priority: "100"
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-strip-cookies@kubernetescrd

spec:
  tls:
    - hosts: [{{ .Values.ingress.host | quote }}]
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /mmate/view
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ .Values.service.port }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-cookies
  namespace: {{ .Release.Namespace }}
spec:
  headers:
    customRequestHeaders:
      Cookie: ""
