name: Build & Push Frontend

on:
  push:
    branches: [main, dev/release-test]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USER }}/mm-app-view:latest .

      - name: Push docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USER }}/mm-app-view:latest
